# permissions for end users to edit simplestatefulsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simplestatefulset-editor-role
rules:
- apiGroups:
  - apps.cncamp.io
  resources:
  - simplestatefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.cncamp.io
  resources:
  - simplestatefulsets/status
  verbs:
  - get
